# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cs2screenshot/protos/cstrike15_gcmessages.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/cs2screenshot/protos/cstrike15_gcmessages.proto\x12\x04\x63sgo\"\xff\x04\n\x19\x43\x45\x63onItemPreviewDataBlock\x12\x11\n\taccountid\x18\x01 \x01(\r\x12\x0e\n\x06itemid\x18\x02 \x01(\x04\x12\x10\n\x08\x64\x65\x66index\x18\x03 \x01(\r\x12\x12\n\npaintindex\x18\x04 \x01(\r\x12\x0e\n\x06rarity\x18\x05 \x01(\r\x12\x0f\n\x07quality\x18\x06 \x01(\r\x12\x11\n\tpaintwear\x18\x07 \x01(\r\x12\x11\n\tpaintseed\x18\x08 \x01(\r\x12\x1a\n\x12killeaterscoretype\x18\t \x01(\r\x12\x16\n\x0ekilleatervalue\x18\n \x01(\r\x12\x12\n\ncustomname\x18\x0b \x01(\t\x12\x39\n\x08stickers\x18\x0c \x03(\x0b\x32\'.csgo.CEconItemPreviewDataBlock.Sticker\x12\x11\n\tinventory\x18\r \x01(\r\x12\x0e\n\x06origin\x18\x0e \x01(\r\x12:\n\tkeychains\x18\x14 \x03(\x0b\x32\'.csgo.CEconItemPreviewDataBlock.Sticker\x12;\n\nvariations\x18\x16 \x03(\x0b\x32\'.csgo.CEconItemPreviewDataBlock.Sticker\x1a\xb2\x01\n\x07Sticker\x12\x0c\n\x04slot\x18\x01 \x01(\r\x12\x12\n\nsticker_id\x18\x02 \x01(\r\x12\x0c\n\x04wear\x18\x03 \x01(\x02\x12\r\n\x05scale\x18\x04 \x01(\x02\x12\x10\n\x08rotation\x18\x05 \x01(\x02\x12\x0f\n\x07tint_id\x18\x06 \x01(\r\x12\x10\n\x08offset_x\x18\x07 \x01(\x02\x12\x10\n\x08offset_y\x18\x08 \x01(\x02\x12\x10\n\x08offset_z\x18\t \x01(\x02\x12\x0f\n\x07pattern\x18\n \x01(\r')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cs2screenshot.protos.cstrike15_gcmessages_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CECONITEMPREVIEWDATABLOCK._serialized_start=58
  _CECONITEMPREVIEWDATABLOCK._serialized_end=697
  _CECONITEMPREVIEWDATABLOCK_STICKER._serialized_start=519
  _CECONITEMPREVIEWDATABLOCK_STICKER._serialized_end=697
# @@protoc_insertion_point(module_scope)
