"""FastAPI backend for the CS2 inspect screenshot tool.

Exposes the existing inspect-link decoder over HTTP and serves the extracted
3D assets (models + textures + paint kit metadata) plus the static web frontend.

Endpoints
---------
- ``POST /api/decode``            body ``{"inspect_link": "..."}`` → decoded item JSON
- ``GET  /api/paintkit/{idx}``    paint kit parameters for a paintindex
- ``GET  /api/paintkits``         full paint kit map (debug)
- ``GET  /assets/*``              extracted GLB models + textures (static)
- ``GET  /*``                     static web frontend (``web/``)

Run with::

    uvicorn cs2screenshot.api:app --reload
    # or
    python -m cs2screenshot.cli serve
"""
from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path
from typing import Any, Optional

import httpx
from fastapi import FastAPI, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import Response
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel

from .decoder import decode

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
REPO_ROOT = Path(__file__).resolve().parent.parent
ASSETS_DIR = REPO_ROOT / "assets"
WEB_DIR = REPO_ROOT / "web"
PAINTKITS_PATH = ASSETS_DIR / "paintkits.json"


# ---------------------------------------------------------------------------
# Request / response models
# ---------------------------------------------------------------------------
class DecodeRequest(BaseModel):
    inspect_link: str


# ---------------------------------------------------------------------------
# Paint kit loading (cached, reloads if file mtime changes)
# ---------------------------------------------------------------------------
@lru_cache(maxsize=1)
def _load_paintkits_cached(mtime: float) -> dict[str, Any]:
    """Load paintkits.json. ``mtime`` is part of the cache key so the cache
    invalidates automatically when the file is regenerated by the extractor."""
    if not PAINTKITS_PATH.exists():
        return {}
    try:
        return json.loads(PAINTKITS_PATH.read_text(encoding="utf-8"))
    except Exception:
        return {}


def load_paintkits() -> dict[str, Any]:
    mtime = PAINTKITS_PATH.stat().st_mtime if PAINTKITS_PATH.exists() else 0.0
    return _load_paintkits_cached(mtime)


# ---------------------------------------------------------------------------
# App
# ---------------------------------------------------------------------------
app = FastAPI(title="CS2 Inspect Screenshot Tool", version="0.1.0")

# Dev-friendly CORS so the frontend can be served from a different origin
# (e.g. a separate static dev server) during development.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.middleware("http")
async def _no_cache_static(request, call_next):
    """Disable browser caching for the frontend during development so edited
    ES modules (web/src/*.js) are always re-fetched on reload."""
    response = await call_next(request)
    path = request.url.path
    if path.endswith((".js", ".css", ".html")) or path == "/":
        response.headers["Cache-Control"] = "no-store, must-revalidate"
    return response


@app.get("/api/health")
def health() -> dict[str, Any]:
    return {
        "status": "ok",
        "assets_dir_exists": ASSETS_DIR.exists(),
        "paintkits_loaded": bool(load_paintkits()),
    }


@app.post("/api/decode")
def decode_endpoint(req: DecodeRequest) -> dict[str, Any]:
    """Decode an inspect link into item parameters (reuses ``decoder.decode``)."""
    try:
        data = decode(req.inspect_link)
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc
    return data.to_dict()


@app.get("/api/paintkit/{paintindex}")
def paintkit_endpoint(paintindex: int) -> dict[str, Any]:
    """Return the paint kit parameters for a given paintindex."""
    kits = load_paintkits()
    kit: Optional[dict[str, Any]] = kits.get(str(paintindex))
    if kit is None:
        raise HTTPException(
            status_code=404,
            detail=f"No paint kit data for paintindex {paintindex}. "
            "Has the extractor (tools/extract) been run?",
        )
    return kit


@app.get("/api/paintkits")
def paintkits_endpoint() -> dict[str, Any]:
    """Return the full paint kit map (debugging / catalog)."""
    return load_paintkits()


# Allow-list of hosts the image proxy may fetch from (sticker/keychain CDNs).
_PROXY_HOSTS = ("cdn.cs2inspects.com", "raw.githubusercontent.com", "steamcdn-a.akamaihd.net")


@app.get("/api/proxy")
def proxy_image(url: str = Query(..., description="Remote image URL to proxy")) -> Response:
    """Same-origin proxy for remote sticker/keychain images.

    Serving these through our origin avoids tainting the WebGL canvas, which
    would otherwise break PNG export (``toDataURL``).
    """
    from urllib.parse import urlparse

    host = urlparse(url).hostname or ""
    if host not in _PROXY_HOSTS:
        raise HTTPException(status_code=400, detail=f"Host not allowed: {host}")
    try:
        with httpx.Client(timeout=8.0, follow_redirects=True) as client:
            r = client.get(url)
            r.raise_for_status()
    except Exception as exc:
        raise HTTPException(status_code=502, detail=f"Proxy fetch failed: {exc}") from exc
    content_type = r.headers.get("content-type", "image/png").split(";")[0]
    return Response(content=r.content, media_type=content_type,
                    headers={"Cache-Control": "public, max-age=86400"})


# ---------------------------------------------------------------------------
# Static mounts (registered last so /api/* takes precedence)
# ---------------------------------------------------------------------------
if ASSETS_DIR.exists():
    app.mount("/assets", StaticFiles(directory=str(ASSETS_DIR)), name="assets")

if WEB_DIR.exists():
    app.mount("/", StaticFiles(directory=str(WEB_DIR), html=True), name="web")
